USB_VID = 0x239A
USB_PID = 0x8060
USB_PRODUCT = "StringCar M0 Express"
USB_MANUFACTURER = "Cedar Grove Studios"
USB_INTERFACE_NAME = "StringCarM0Ex"

CHIP_VARIANT = SAMD21E18A
CHIP_FAMILY = samd21

SPI_FLASH_FILESYSTEM = 1
EXTERNAL_FLASH_DEVICES = AT25SF161
LONGINT_IMPL = MPZ

CIRCUITPY_USB_MIDI = 0

CIRCUITPY_BITBANG_APA102 = 1

CIRCUITPY_FULL_BUILD = 0
MICROPY_PY_ASYNC_AWAIT = 1
CIRCUITPY_AESIO = 0
CIRCUITPY_ATEXIT = 1
CIRCUITPY_AUDIOBUSIO = 0
CIRCUITPY_AUDIOIO = 0
CIRCUITPY_AUDIOMP3 = 0
CIRCUITPY_BINASCII = 0
CIRCUITPY_BITBANGIO = 1
CIRCUITPY_BLEIO_HCI = 0
CIRCUITPY_BUSDEVICE = 1
CIRCUITPY_BUILTINS_POW3 = 0
CIRCUITPY_CODEOP = 0
CIRCUITPY_COUNTIO = 1
CIRCUITPY_DISPLAYIO = 1
CIRCUITPY_OS_GETENV = 1
CIRCUITPY_ERRNO = 1
CIRCUITPY_FREQUENCYIO = 1
CIRCUITPY_GETPASS = 0
CIRCUITPY_I2CTARGET = 0
CIRCUITPY_JSON = 0
CIRCUITPY_KEYPAD = 0
CIRCUITPY_LOCALE = 1
CIRCUITPY_MSGPACK = 0
CIRCUITPY_OPT_MAP_LOOKUP_CACHE = 1
CIRCUITPY_PULSEIO = 1
CIRCUITPY_RE = 0
CIRCUITPY_SDCARDIO = 1
CIRCUITPY_TRACEBACK = 1
CIRCUITPY_ZLIB = 0
CIRCUITPY_ULAB = 0
CIRCUITPY_WARNINGS = 1
