USB_VID = 0x30A4
USB_PID = 0x03
USB_PRODUCT = "Cygnet"
USB_MANUFACTURER = "Blues Inc."

MCU_SERIES = L4
MCU_VARIANT = STM32L433xx
MCU_PACKAGE = LQFP48

LD_COMMON = boards/common_default.ld
LD_DEFAULT = boards/STM32L433_default.ld
UF2_OFFSET = 0x8000000
UF2_BOOTLOADER ?= 0
CIRCUITPY_BUILD_EXTENSIONS = bin

INTERNAL_FLASH_FILESYSTEM = 1
LONGINT_IMPL = NONE
CIRCUITPY_FULL_BUILD = 0

CIRCUITPY_AESIO = 0
CIRCUITPY_ALARM = 0
CIRCUITPY_ANALOGIO = 1
CIRCUITPY_ATEXIT = 0
CIRCUITPY_AUDIOBUSIO = 0
CIRCUITPY_AUDIOBUSIO_I2SOUT = 0
CIRCUITPY_AUDIOBUSIO_PDMIN = 0
CIRCUITPY_AUDIOMIXER = 0
CIRCUITPY_AUDIOMP3 = 0
CIRCUITPY_AUDIOPWMIO = 0
CIRCUITPY_BITBANGIO = 1
CIRCUITPY_BLEIO = 0
CIRCUITPY_BLEIO_HCI = 0
CIRCUITPY_BINASCII = 0
CIRCUITPY_BITMAPFILTER = 0
CIRCUITPY_BITMAPTOOLS = 0
CIRCUITPY_BUILTINS_POW3 = 0
CIRCUITPY_BUSDEVICE = 0
CIRCUITPY_BUSIO = 1
CIRCUITPY_CANIO = 0
CIRCUITPY_COMPUTED_GOTO_SAVE_SPACE = 1
CIRCUITPY_COUNTIO = 0
CIRCUITPY_DIGITALIO = 1
CIRCUITPY_DISPLAYIO = 0
CIRCUITPY_ENABLE_MPY_NATIVE = 0
CIRCUITPY_FRAMEBUFFERIO = 0
CIRCUITPY_FREQUENCYIO = 0
CIRCUITPY_FUTURE= 0
CIRCUITPY_GETPASS = 0
CIRCUITPY_GIFIO = 0
CIRCUITPY_I2CTARGET = 0
CIRCUITPY_JSON = 0
CIRCUITPY_KEYPAD = 0
CIRCUITPY_KEYPAD_DEMUX = 0
CIRCUITPY_LTO = 1
CIRCUITPY_MICROCONTROLLER = 1
CIRCUITPY_MSGPACK = 0
CIRCUITPY_NEOPIXEL_WRITE = 0
CIRCUITPY_NVM = 0
CIRCUITPY_ONEWIREIO = 0
CIRCUITPY_OS = 1
CIRCUITPY_PIXELBUF = 0
CIRCUITPY_PIXELMAP = 0
CIRCUITPY_PULSEIO = 1
CIRCUITPY_PWMIO = 1
CIRCUITPY_RANDOM = 0
CIRCUITPY_RAINBOWIO = 0
CIRCUITPY_RE = 0
CIRCUITPY_REQUIRE_I2C_PULLUPS = 0
CIRCUITPY_ROTARYIO_SOFTENCODER = 1
CIRCUITPY_RGBMATRIX = 0
CIRCUITPY_RTC = 0
CIRCUITPY_SAFEMODE_PY = 0
CIRCUITPY_SDCARDIO = 0
CIRCUITPY_STATUS_BAR= 0
CIRCUITPY_STORAGE = 1
CIRCUITPY_SUPERVISOR = 1
CIRCUITPY_SYNTHIO = 0
CIRCUITPY_TERMINALIO = 0
CIRCUITPY_TOUCHIO = 0
CIRCUITPY_TOUCHIO_USE_NATIVE = 1
CIRCUITPY_TRACEBACK = 0
CIRCUITPY_ULAB = 0
CIRCUITPY_USB_CDC = 1
CIRCUITPY_USB_HID = 0
CIRCUITPY_USB_IDENTIFICATION = 1
CIRCUITPY_USB_MIDI = 0
CIRCUITPY_USB_MIDI_ENABLED_DEFAULT= 0
CIRCUITPY_USB_MSC = 1
CIRCUITPY_USB_VENDOR = 0
CIRCUITPY_WIFI_RADIO_SETTABLE_MAC_ADDRESS= 0
CIRCUITPY_VECTORIO = 0
CIRCUITPY_ZLIB = 0

MICROPY_PY_ASYNC_AWAIT = 0

RELEASE_NEEDS_CLEAN_BUILD = 0

SUPEROPT_GC = 0
SUPEROPT_VM = 0

CIRCUITPY_LTO_PARTITION = one

OPTIMIZATION_FLAGS = -Os

CFLAGS_BOARD = -fweb -frename-registers
