USB_VID = 0x046D
USB_PID = 0xC08B
USB_PRODUCT = "G903 LIGHTSPEED Wireless Gaming Mouse"
USB_MANUFACTURER = "Logitech"

CIRCUITPY_USB_HID_DEVICES = "MOUSE"

CIRCUITPY_USB_MSC = 0
CIRCUITPY_USB_CDC = 0
CIRCUITPY_AUDIO_CORE = 0 # Nur einmal!

CHIP_VARIANT = RP2040
CHIP_FAMILY = rp2
EXTERNAL_FLASH_DEVICES = "W25Q16JVxQ"
CIRCUITPY__EVE = 1
CIRCUITPY_PICODVI = 1

