# This file was generated by gen_compat2driver.py
COMPAT_TO_DRIVER = {
    # adc
    "adi_ad4114_adc": "adc",
    "adi_ad559x_adc": "adc",
    "adi_max32_adc": "adc",
    "ambiq_adc": "adc",
    "atmel_sam0_adc": "adc",
    "atmel_sam_adc": "adc",
    "atmel_sam_afec": "adc",
    "ene_kb1200_adc": "adc",
    "espressif_esp32_adc": "adc",
    "gd_gd32_adc": "adc",
    "infineon_cat1_adc": "adc",
    "infineon_xmc4xxx_adc": "adc",
    "ite_it8xxx2_adc": "adc",
    "lltc_ltc2451": "adc",
    "maxim_max11102": "adc",
    "maxim_max11103": "adc",
    "maxim_max11105": "adc",
    "maxim_max11106": "adc",
    "maxim_max11110": "adc",
    "maxim_max11111": "adc",
    "maxim_max11115": "adc",
    "maxim_max11116": "adc",
    "maxim_max11117": "adc",
    "maxim_max11253": "adc",
    "maxim_max11254": "adc",
    "microchip_xec_adc": "adc",
    "nordic_nrf_adc": "adc",
    "nordic_nrf_saadc": "adc",
    "nuvoton_npcx_adc": "adc",
    "nuvoton_numaker_adc": "adc",
    "nxp_adc12": "adc",
    "nxp_gau_adc": "adc",
    "nxp_kinetis_adc16": "adc",
    "nxp_lpc_lpadc": "adc",
    "nxp_mcux_12b1msps_sar": "adc",
    "nxp_s32_adc_sar": "adc",
    "nxp_vf610_adc": "adc",
    "raspberrypi_pico_adc": "adc",
    "renesas_ra_adc": "adc",
    "renesas_smartbond_adc": "adc",
    "renesas_smartbond_sdadc": "adc",
    "silabs_gecko_adc": "adc",
    "silabs_gecko_iadc": "adc",
    "st_stm32_adc": "adc",
    "st_stm32wb0_adc": "adc",
    "telink_b91_adc": "adc",
    "ti_ads1013": "adc",
    "ti_ads1014": "adc",
    "ti_ads1015": "adc",
    "ti_ads1112": "adc",
    "ti_ads1113": "adc",
    "ti_ads1114": "adc",
    "ti_ads1115": "adc",
    "ti_ads1119": "adc",
    "ti_ads114s08": "adc",
    "ti_ads131m02": "adc",
    "ti_ads7052": "adc",
    "ti_cc13xx_cc26xx_adc": "adc",
    "ti_cc32xx_adc": "adc",
    "ti_lmp90077": "adc",
    "ti_lmp90078": "adc",
    "ti_lmp90079": "adc",
    "ti_lmp90080": "adc",
    "ti_lmp90097": "adc",
    "ti_lmp90098": "adc",
    "ti_lmp90099": "adc",
    "ti_lmp90100": "adc",
    "ti_tla2021": "adc",
    "ti_tla2022": "adc",
    "ti_tla2024": "adc",
    "vnd_adc": "adc",
    "zephyr_adc_emul": "adc",
    #
    # audio
    "nxp_dmic": "audio",
    "st_mpxxdtyy": "audio",
    "ti_tas6422dac": "audio",
    "ti_tlv320dac": "audio",
    "wolfson_wm8904": "audio",
    #
    # auxdisplay
    "hit_hd44780": "auxdisplay",
    "jhd_jhd1313": "auxdisplay",
    "noritake_itron": "auxdisplay",
    "ptc_pt6314": "auxdisplay",
    "sparkfun_serlcd": "auxdisplay",
    #
    # bbram
    "ite_it8xxx2_bbram": "bbram",
    "microchip_xec_bbram": "bbram",
    "nuvoton_npcx_bbram": "bbram",
    "st_stm32_bbram": "bbram",
    "zephyr_bbram_emul": "bbram",
    #
    # bluetooth/hci
    "ambiq_bt_hci_spi": "bluetooth/hci",
    "espressif_esp32_bt_hci": "bluetooth/hci",
    "infineon_cat1_bless_hci": "bluetooth/hci",
    "infineon_cyw208xx_hci": "bluetooth/hci",
    "infineon_cyw43xxx_bt_hci": "bluetooth/hci",
    "nxp_bt_hci_uart": "bluetooth/hci",
    "nxp_hci_ble": "bluetooth/hci",
    "renesas_bt_hci_da1453x": "bluetooth/hci",
    "renesas_bt_hci_da1469x": "bluetooth/hci",
    "silabs_bt_hci_efr32": "bluetooth/hci",
    "st_hci_spi_v1": "bluetooth/hci",
    "st_hci_spi_v2": "bluetooth/hci",
    "st_hci_stm32wb0": "bluetooth/hci",
    "st_hci_stm32wba": "bluetooth/hci",
    "st_stm32wb_rf": "bluetooth/hci",
    "zephyr_bt_hci_3wire_uart": "bluetooth/hci",
    "zephyr_bt_hci_ipc": "bluetooth/hci",
    "zephyr_bt_hci_spi": "bluetooth/hci",
    "zephyr_bt_hci_uart": "bluetooth/hci",
    "zephyr_bt_hci_userchan": "bluetooth/hci",
    #
    # can
    "atmel_sam0_can": "can",
    "atmel_sam_can": "can",
    "espressif_esp32_twai": "can",
    "infineon_xmc4xxx_can_node": "can",
    "kvaser_pcican": "can",
    "microchip_mcp2515": "can",
    "microchip_mcp251xfd": "can",
    "nordic_nrf_can": "can",
    "nuvoton_numaker_canfd": "can",
    "nxp_flexcan": "can",
    "nxp_lpc_mcan": "can",
    "nxp_s32_canxl": "can",
    "renesas_ra_canfd": "can",
    "renesas_rcar_can": "can",
    "st_stm32_bxcan": "can",
    "st_stm32_fdcan": "can",
    "st_stm32h7_fdcan": "can",
    "ti_tcan4x5x": "can",
    "zephyr_can_loopback": "can",
    "zephyr_fake_can": "can",
    "zephyr_native_linux_can": "can",
    #
    # can/transceiver
    "can_transceiver_gpio": "can/transceiver",
    #
    # charger
    "maxim_max20335_charger": "charger",
    "sbs_sbs_charger": "charger",
    "ti_bq24190": "charger",
    "ti_bq25180": "charger",
    #
    # clock_control
    "adi_max32_gcr": "clock_control",
    "ambiq_clkctrl": "clock_control",
    "arm_beetle_syscon": "clock_control",
    "arm_scmi_clock": "clock_control",
    "aspeed_ast10x0_clock": "clock_control",
    "atmel_sam_pmc": "clock_control",
    "espressif_esp32_rtc": "clock_control",
    "fixed_clock": "clock_control",
    "gd_gd32_cctl": "clock_control",
    "intel_agilex5_clock": "clock_control",
    "microchip_xec_pcr": "clock_control",
    "nordic_nrf54h_hfxo": "clock_control",
    "nordic_nrf_auxpll": "clock_control",
    "nordic_nrf_clock": "clock_control",
    "nordic_nrf_fll16m": "clock_control",
    "nordic_nrf_hsfll_global": "clock_control",
    "nordic_nrf_hsfll_local": "clock_control",
    "nordic_nrf_lfclk": "clock_control",
    "nuvoton_npcm_pcc": "clock_control",
    "nuvoton_npcx_pcc": "clock_control",
    "nuvoton_numaker_scc": "clock_control",
    "nxp_imx_ccm": "clock_control",
    "nxp_imx_ccm_rev2": "clock_control",
    "nxp_kinetis_mcg": "clock_control",
    "nxp_kinetis_pcc": "clock_control",
    "nxp_kinetis_scg": "clock_control",
    "nxp_kinetis_sim": "clock_control",
    "nxp_lpc11u6x_syscon": "clock_control",
    "nxp_lpc_syscon": "clock_control",
    "nxp_s32_clock": "clock_control",
    "nxp_scg_k4": "clock_control",
    "openisa_rv32m1_pcc": "clock_control",
    "pwm_clock": "clock_control",
    "raspberrypi_pico_clock_controller": "clock_control",
    "realtek_rts5912_sccon": "clock_control",
    "renesas_r8a7795_cpg_mssr": "clock_control",
    "renesas_r8a779f0_cpg_mssr": "clock_control",
    "silabs_series_clock": "clock_control",
    "silabs_si32_ahb": "clock_control",
    "silabs_si32_apb": "clock_control",
    "silabs_si32_pll": "clock_control",
    "smartbond_clock": "clock_control",
    "st_stm32_clock_mco": "clock_control",
    "st_stm32_clock_mux": "clock_control",
    "st_stm32f1_clock_mco": "clock_control",
    "wch_rcc": "clock_control",
    #
    # comparator
    "nordic_nrf_comp": "comparator",
    "nordic_nrf_lpcomp": "comparator",
    "zephyr_fake_comp": "comparator",
    #
    # coredump
    "zephyr_coredump": "coredump",
    #
    # counter
    "adi_max32_counter": "counter",
    "adi_max32_rtc_counter": "counter",
    "ambiq_counter": "counter",
    "andestech_atcpit100": "counter",
    "arm_cmsdk_dtimer": "counter",
    "arm_cmsdk_timer": "counter",
    "atmel_sam0_tc32": "counter",
    "atmel_sam_tc": "counter",
    "espressif_esp32_rtc_timer": "counter",
    "espressif_esp32_timer": "counter",
    "gd_gd32_timer": "counter",
    "infineon_cat1_counter": "counter",
    "maxim_ds3231": "counter",
    "microchip_mcp7940n": "counter",
    "microchip_xec_timer": "counter",
    "nordic_nrf_rtc": "counter",
    "nordic_nrf_timer": "counter",
    "nxp_imx_epit": "counter",
    "nxp_imx_gpt": "counter",
    "nxp_imx_qtmr": "counter",
    "nxp_imx_snvs_rtc": "counter",
    "nxp_imx_tmr": "counter",
    "nxp_lpc_ctimer": "counter",
    "nxp_lpc_rtc": "counter",
    "nxp_lpc_rtc_highres": "counter",
    "nxp_mrt": "counter",
    "nxp_pit": "counter",
    "nxp_rtc": "counter",
    "nxp_s32_sys_timer": "counter",
    "nxp_tpm_timer": "counter",
    "raspberrypi_pico_timer": "counter",
    "renesas_ra_agt_counter": "counter",
    "renesas_smartbond_timer": "counter",
    "silabs_gecko_rtcc": "counter",
    "silabs_gecko_stimer": "counter",
    "snps_dw_timers": "counter",
    "st_stm32_counter": "counter",
    "xlnx_xps_timer_1_00_a": "counter",
    "zephyr_native_posix_counter": "counter",
    #
    # crypto
    "atmel_ataes132a": "crypto",
    "intel_adsp_sha": "crypto",
    "ite_it8xxx2_sha": "crypto",
    "ite_it8xxx2_sha_v2": "crypto",
    "microchip_xec_symcr": "crypto",
    "nordic_nrf_ecb": "crypto",
    "nuvoton_npcx_sha": "crypto",
    "nxp_mcux_dcp": "crypto",
    "renesas_smartbond_crypto": "crypto",
    "silabs_si32_aes": "crypto",
    "st_stm32_aes": "crypto",
    "st_stm32_cryp": "crypto",
    #
    # dac
    "adi_ad559x_dac": "dac",
    "adi_ad5628": "dac",
    "adi_ad5648": "dac",
    "adi_ad5668": "dac",
    "adi_ad5672": "dac",
    "adi_ad5674": "dac",
    "adi_ad5676": "dac",
    "adi_ad5679": "dac",
    "adi_ad5684": "dac",
    "adi_ad5686": "dac",
    "adi_ad5687": "dac",
    "adi_ad5689": "dac",
    "adi_ad5691": "dac",
    "adi_ad5692": "dac",
    "adi_ad5693": "dac",
    "adi_max22017_dac": "dac",
    "atmel_sam0_dac": "dac",
    "atmel_sam_dac": "dac",
    "espressif_esp32_dac": "dac",
    "gd_gd32_dac": "dac",
    "microchip_mcp4725": "dac",
    "microchip_mcp4728": "dac",
    "nxp_gau_dac": "dac",
    "nxp_kinetis_dac": "dac",
    "nxp_kinetis_dac32": "dac",
    "nxp_lpdac": "dac",
    "st_stm32_dac": "dac",
    "ti_dacx0501": "dac",
    "vnd_dac": "dac",
    #
    # dai/intel/alh
    "intel_alh_dai": "dai/intel/alh",
    #
    # dai/intel/dmic
    "intel_dai_dmic": "dai/intel/dmic",
    #
    # dai/intel/hda
    "intel_hda_dai": "dai/intel/hda",
    #
    # dai/intel/ssp
    "intel_ssp_dai": "dai/intel/ssp",
    #
    # dai/nxp/sai
    "nxp_dai_sai": "dai/nxp/sai",
    #
    # disk
    "st_stm32_sdmmc": "disk",
    "zephyr_flash_disk": "disk",
    "zephyr_mmc_disk": "disk",
    "zephyr_ram_disk": "disk",
    "zephyr_sdmmc_disk": "disk",
    #
    # disk/nvme
    "nvme_controller": "disk/nvme",
    #
    # display
    "frida_nt35510": "display",
    "galaxycore_gc9x01x": "display",
    "himax_hx8394": "display",
    "ilitek_ili9806e_dsi": "display",
    "intel_multiboot_framebuffer": "display",
    "istech_ist3931": "display",
    "led_strip_matrix": "display",
    "maxim_max7219": "display",
    "nxp_dcnano_lcdif": "display",
    "nxp_imx_elcdif": "display",
    "orisetech_otm8009a": "display",
    "raydium_rm67162": "display",
    "raydium_rm68200": "display",
    "renesas_ra_glcdc": "display",
    "renesas_smartbond_display": "display",
    "sharp_ls0xx": "display",
    "sitronix_st7735r": "display",
    "sitronix_st7789v": "display",
    "sitronix_st7796s": "display",
    "solomon_ssd1322": "display",
    "st_stm32_ltdc": "display",
    "zephyr_dummy_dc": "display",
    "zephyr_sdl_dc": "display",
    #
    # dma
    "adi_max32_dma": "dma",
    "altr_msgdma": "dma",
    "andestech_atcdmac300": "dma",
    "atmel_sam0_dmac": "dma",
    "atmel_sam_xdmac": "dma",
    "brcm_iproc_pax_dma_v1": "dma",
    "brcm_iproc_pax_dma_v2": "dma",
    "espressif_esp32_gdma": "dma",
    "gd_gd32_dma": "dma",
    "gd_gd32_dma_v1": "dma",
    "infineon_cat1_dma": "dma",
    "infineon_xmc4xxx_dma": "dma",
    "intel_adsp_gpdma": "dma",
    "intel_adsp_hda_host_in": "dma",
    "intel_adsp_hda_host_out": "dma",
    "intel_adsp_hda_link_in": "dma",
    "intel_adsp_hda_link_out": "dma",
    "intel_lpss": "dma",
    "intel_sedi_dma": "dma",
    "microchip_xec_dmac": "dma",
    "nxp_lpc_dma": "dma",
    "nxp_mcux_edma": "dma",
    "nxp_pxp": "dma",
    "nxp_sdma": "dma",
    "nxp_smartdma": "dma",
    "nxp_sof_host_dma": "dma",
    "raspberrypi_pico_dma": "dma",
    "renesas_smartbond_dma": "dma",
    "silabs_ldma": "dma",
    "silabs_si32_dma": "dma",
    "snps_designware_dma": "dma",
    "snps_designware_dma_axi": "dma",
    "st_stm32_bdma": "dma",
    "st_stm32_dma_v1": "dma",
    "st_stm32_dma_v2": "dma",
    "st_stm32_dma_v2bis": "dma",
    "st_stm32_dmamux": "dma",
    "st_stm32u5_dma": "dma",
    "xlnx_axi_dma_1_00_a": "dma",
    "xlnx_eth_dma": "dma",
    "zephyr_dma_emul": "dma",
    #
    # dp
    "zephyr_swdp_gpio": "dp",
    #
    # edac
    "intel_ibecc": "edac",
    #
    # eeprom
    "atmel_at24": "eeprom",
    "fujitsu_mb85rcxx": "eeprom",
    "fujitsu_mb85rsxx": "eeprom",
    "microchip_xec_eeprom": "eeprom",
    "nxp_lpc11u6x_eeprom": "eeprom",
    "st_stm32_eeprom": "eeprom",
    "ti_tmp116_eeprom": "eeprom",
    "zephyr_emu_eeprom": "eeprom",
    "zephyr_fake_eeprom": "eeprom",
    "zephyr_sim_eeprom": "eeprom",
    #
    # entropy
    "adi_max32_trng": "entropy",
    "atmel_sam_trng": "entropy",
    "espressif_esp32_trng": "entropy",
    "litex_prbs": "entropy",
    "neorv32_trng": "entropy",
    "nordic_nrf_rng": "entropy",
    "nuvoton_npcx_drbg": "entropy",
    "nxp_imx_caam": "entropy",
    "nxp_kinetis_rnga": "entropy",
    "nxp_kinetis_trng": "entropy",
    "nxp_lpc_rng": "entropy",
    "openisa_rv32m1_trng": "entropy",
    "renesas_smartbond_trng": "entropy",
    "silabs_gecko_semailbox": "entropy",
    "silabs_gecko_trng": "entropy",
    "st_stm32_rng": "entropy",
    "telink_b91_trng": "entropy",
    "ti_cc13xx_cc26xx_trng": "entropy",
    "zephyr_bt_hci_entropy": "entropy",
    "zephyr_native_posix_rng": "entropy",
    "zephyr_psa_crypto_rng": "entropy",
    #
    # espi
    "ite_it8xxx2_espi": "espi",
    "microchip_xec_espi": "espi",
    "microchip_xec_espi_host_dev": "espi",
    "microchip_xec_espi_saf": "espi",
    "microchip_xec_espi_saf_v2": "espi",
    "microchip_xec_espi_v2": "espi",
    "nuvoton_npcx_espi": "espi",
    "nuvoton_npcx_espi_taf": "espi",
    "nuvoton_npcx_host_sub": "espi",
    "zephyr_espi_emul_controller": "espi",
    #
    # ethernet
    "adi_adin1110": "ethernet",
    "adi_adin2111": "ethernet",
    "atmel_sam0_gmac": "ethernet",
    "atmel_sam_gmac": "ethernet",
    "espressif_esp32_eth": "ethernet",
    "infineon_xmc4xxx_ethernet": "ethernet",
    "intel_e1000": "ethernet",
    "litex_liteeth": "ethernet",
    "microchip_enc28j60": "ethernet",
    "microchip_enc424j600": "ethernet",
    "microchip_ksz8794": "ethernet",
    "microchip_ksz8863": "ethernet",
    "microchip_lan865x": "ethernet",
    "microchip_lan9250": "ethernet",
    "nuvoton_numaker_ethernet": "ethernet",
    "nxp_imx_netc_psi": "ethernet",
    "nxp_s32_gmac": "ethernet",
    "nxp_s32_netc_psi": "ethernet",
    "nxp_s32_netc_vsi": "ethernet",
    "renesas_ra_ethernet": "ethernet",
    "siemens_ivshmem_eth": "ethernet",
    "silabs_gecko_ethernet": "ethernet",
    "smsc_lan91c111": "ethernet",
    "smsc_lan9220": "ethernet",
    "snps_designware_ethernet": "ethernet",
    "snps_ethernet_cyclonev": "ethernet",
    "st_stm32_ethernet": "ethernet",
    "ti_stellaris_ethernet": "ethernet",
    "vnd_ethernet": "ethernet",
    "wiznet_w5500": "ethernet",
    #
    # ethernet/dwc_xgmac
    "snps_dwcxgmac": "ethernet/dwc_xgmac",
    #
    # ethernet/eth_nxp_enet_qos
    "nxp_enet_qos": "ethernet/eth_nxp_enet_qos",
    "nxp_enet_qos_mac": "ethernet/eth_nxp_enet_qos",
    #
    # ethernet/nxp_enet
    "nxp_enet": "ethernet/nxp_enet",
    "nxp_enet1g": "ethernet/nxp_enet",
    "nxp_enet_mac": "ethernet/nxp_enet",
    "nxp_kinetis_ethernet": "ethernet/nxp_enet",
    #
    # ethernet/phy
    "adi_adin1100_phy": "ethernet/phy",
    "adi_adin2111_phy": "ethernet/phy",
    "davicom_dm8806_phy": "ethernet/phy",
    "ethernet_phy": "ethernet/phy",
    "microchip_ksz8081": "ethernet/phy",
    "microchip_t1s_phy": "ethernet/phy",
    "microchip_vsc8541": "ethernet/phy",
    "nxp_tja1103": "ethernet/phy",
    "qca_ar8031": "ethernet/phy",
    "realtek_rtl8211f": "ethernet/phy",
    "ti_dp83825": "ethernet/phy",
    #
    # firmware/scmi
    "arm_scmi_shmem": "firmware/scmi",
    #
    # flash
    "adi_max32_flash_controller": "flash",
    "altr_nios2_qspi_nor": "flash",
    "ambiq_flash_controller": "flash",
    "andestech_qspi_nor": "flash",
    "atmel_at45": "flash",
    "atmel_sam0_nvmctrl": "flash",
    "atmel_sam_flash_controller": "flash",
    "cdns_nand": "flash",
    "cdns_qspi_nor": "flash",
    "espressif_esp32_flash_controller": "flash",
    "gd_gd32_flash_controller": "flash",
    "infineon_cat1_flash_controller": "flash",
    "infineon_cat1_qspi_flash": "flash",
    "infineon_xmc4xxx_flash_controller": "flash",
    "ite_it8xxx2_flash_controller": "flash",
    "jedec_spi_nor": "flash",
    "mspi_atxp032": "flash",
    "nordic_mram": "flash",
    "nordic_nrf51_flash_controller": "flash",
    "nordic_nrf52_flash_controller": "flash",
    "nordic_nrf53_flash_controller": "flash",
    "nordic_nrf91_flash_controller": "flash",
    "nordic_qspi_nor": "flash",
    "nordic_rram_controller": "flash",
    "nuvoton_npcx_fiu_nor": "flash",
    "nuvoton_npcx_fiu_qspi": "flash",
    "nuvoton_numaker_fmc": "flash",
    "nuvoton_numaker_rmc": "flash",
    "nxp_iap_fmc11": "flash",
    "nxp_iap_fmc54": "flash",
    "nxp_iap_fmc55": "flash",
    "nxp_iap_fmc553": "flash",
    "nxp_imx_flexspi_hyperflash": "flash",
    "nxp_imx_flexspi_mx25um51345g": "flash",
    "nxp_imx_flexspi_nor": "flash",
    "nxp_kinetis_ftfa": "flash",
    "nxp_kinetis_ftfe": "flash",
    "nxp_kinetis_ftfl": "flash",
    "nxp_msf1": "flash",
    "nxp_s32_qspi_nor": "flash",
    "openisa_rv32m1_ftfe": "flash",
    "raspberrypi_pico_flash_controller": "flash",
    "renesas_ra_flash_hp_controller": "flash",
    "renesas_ra_ospi_b_nor": "flash",
    "renesas_ra_qspi_nor": "flash",
    "renesas_smartbond_flash_controller": "flash",
    "silabs_gecko_flash_controller": "flash",
    "silabs_si32_flash_controller": "flash",
    "st_stm32_flash_controller": "flash",
    "st_stm32_ospi_nor": "flash",
    "st_stm32_qspi_nor": "flash",
    "st_stm32_xspi_nor": "flash",
    "st_stm32h7_flash_controller": "flash",
    "st_stm32wb0_flash_controller": "flash",
    "st_stm32wba_flash_controller": "flash",
    "telink_b91_flash_controller": "flash",
    "ti_cc13xx_cc26xx_flash_controller": "flash",
    "zephyr_mspi_emul_flash": "flash",
    "zephyr_sim_flash": "flash",
    #
    # fpga
    "altr_socfpga_agilex_bridge": "fpga",
    "lattice_ice40_fpga": "fpga",
    "lattice_ice40_fpga_bitbang": "fpga",
    "microchip_mpfs_mailbox": "fpga",
    "renesas_slg47105": "fpga",
    "renesas_slg47115": "fpga",
    "xlnx_fpga": "fpga",
    #
    # fuel_gauge/bq27z746
    "ti_bq27z746": "fuel_gauge/bq27z746",
    #
    # fuel_gauge/composite
    "zephyr_fuel_gauge_composite": "fuel_gauge/composite",
    #
    # fuel_gauge/max17048
    "maxim_max17048": "fuel_gauge/max17048",
    #
    # fuel_gauge/sbs_gauge
    "sbs_sbs_gauge": "fuel_gauge/sbs_gauge",
    "sbs_sbs_gauge_new_api": "fuel_gauge/sbs_gauge",
    #
    # gnss
    "gnss_nmea_generic": "gnss",
    "luatos_air530z": "gnss",
    "quectel_lc26g": "gnss",
    "quectel_lc76g": "gnss",
    "quectel_lc86g": "gnss",
    "u_blox_m8": "gnss",
    "zephyr_gnss_emul": "gnss",
    #
    # gpio
    "adi_ad559x_gpio": "gpio",
    "adi_adp5585_gpio": "gpio",
    "adi_max14906_gpio": "gpio",
    "adi_max14916_gpio": "gpio",
    "adi_max22017_gpio": "gpio",
    "adi_max22190_gpio": "gpio",
    "adi_max32_gpio": "gpio",
    "altr_pio_1_0": "gpio",
    "ambiq_gpio_bank": "gpio",
    "andestech_atcgpio100": "gpio",
    "arm_cmsdk_gpio": "gpio",
    "atmel_sam0_gpio": "gpio",
    "atmel_sam4l_gpio": "gpio",
    "atmel_sam_gpio": "gpio",
    "awinic_aw9523b_gpio": "gpio",
    "brcm_bcm2711_gpio": "gpio",
    "brcm_brcmstb_gpio": "gpio",
    "brcm_iproc_gpio": "gpio",
    "cypress_cy8c95xx_gpio_port": "gpio",
    "cypress_psoc6_gpio": "gpio",
    "efinix_sapphire_gpio": "gpio",
    "ene_kb1200_gpio": "gpio",
    "espressif_esp32_gpio": "gpio",
    "fcs_fxl6408": "gpio",
    "gaisler_grgpio": "gpio",
    "gd_gd32_gpio": "gpio",
    "infineon_cat1_gpio": "gpio",
    "infineon_tle9104_gpio": "gpio",
    "infineon_xmc4xxx_gpio": "gpio",
    "intel_gpio": "gpio",
    "intel_sedi_gpio": "gpio",
    "ite_it8801_gpio": "gpio",
    "ite_it8xxx2_gpio": "gpio",
    "ite_it8xxx2_gpio_v2": "gpio",
    "ite_it8xxx2_gpiokscan": "gpio",
    "litex_gpio": "gpio",
    "microchip_mcp23008": "gpio",
    "microchip_mcp23009": "gpio",
    "microchip_mcp23016": "gpio",
    "microchip_mcp23017": "gpio",
    "microchip_mcp23018": "gpio",
    "microchip_mcp23s08": "gpio",
    "microchip_mcp23s09": "gpio",
    "microchip_mcp23s17": "gpio",
    "microchip_mcp23s18": "gpio",
    "microchip_mec5_gpio": "gpio",
    "microchip_mpfs_gpio": "gpio",
    "microchip_xec_gpio": "gpio",
    "microchip_xec_gpio_v2": "gpio",
    "neorv32_gpio": "gpio",
    "nordic_npm1300_gpio": "gpio",
    "nordic_npm2100_gpio": "gpio",
    "nordic_npm6001_gpio": "gpio",
    "nordic_nrf_gpio": "gpio",
    "nuvoton_nct38xx_gpio": "gpio",
    "nuvoton_nct38xx_gpio_alert": "gpio",
    "nuvoton_nct38xx_gpio_port": "gpio",
    "nuvoton_npcx_gpio": "gpio",
    "nuvoton_numaker_gpio": "gpio",
    "nuvoton_numicro_gpio": "gpio",
    "nxp_imx_gpio": "gpio",
    "nxp_imx_rgpio": "gpio",
    "nxp_kinetis_gpio": "gpio",
    "nxp_lpc11u6x_gpio": "gpio",
    "nxp_lpc_gpio_port": "gpio",
    "nxp_pca9538": "gpio",
    "nxp_pca9539": "gpio",
    "nxp_pca9554": "gpio",
    "nxp_pca9555": "gpio",
    "nxp_pca95xx": "gpio",
    "nxp_pcal6408a": "gpio",
    "nxp_pcal6416a": "gpio",
    "nxp_pcal6524": "gpio",
    "nxp_pcal6534": "gpio",
    "nxp_pcf857x": "gpio",
    "nxp_s32_gpio": "gpio",
    "nxp_sc18im704_gpio": "gpio",
    "openisa_rv32m1_gpio": "gpio",
    "quicklogic_eos_s3_gpio": "gpio",
    "raspberrypi_pico_gpio": "gpio",
    "raspberrypi_rp1_gpio": "gpio",
    "realtek_rts5912_gpio": "gpio",
    "renesas_ra_gpio": "gpio",
    "renesas_ra_gpio_ioport": "gpio",
    "renesas_rcar_gpio": "gpio",
    "renesas_rz_gpio": "gpio",
    "renesas_rzt2m_gpio": "gpio",
    "renesas_smartbond_gpio": "gpio",
    "richtek_rt1718s": "gpio",
    "richtek_rt1718s_gpio_port": "gpio",
    "rohm_bd8lb600fs_gpio": "gpio",
    "semtech_sx1509b": "gpio",
    "sensry_sy1xx_gpio": "gpio",
    "sifive_gpio0": "gpio",
    "silabs_gecko_gpio_port": "gpio",
    "silabs_si32_gpio": "gpio",
    "snps_creg_gpio": "gpio",
    "snps_designware_gpio": "gpio",
    "st_stm32_gpio": "gpio",
    "st_stmpe1600": "gpio",
    "telink_b91_gpio": "gpio",
    "ti_ads114s0x_gpio": "gpio",
    "ti_cc13xx_cc26xx_gpio": "gpio",
    "ti_cc32xx_gpio": "gpio",
    "ti_davinci_gpio": "gpio",
    "ti_lmp90xxx_gpio": "gpio",
    "ti_sn74hc595": "gpio",
    "ti_stellaris_gpio": "gpio",
    "ti_tca6424a": "gpio",
    "ti_tca9538": "gpio",
    "vnd_gpio": "gpio",
    "wch_gpio": "gpio",
    "x_powers_axp192_gpio": "gpio",
    "xlnx_ps_gpio": "gpio",
    "xlnx_ps_gpio_bank": "gpio",
    "xlnx_xps_gpio_1_00_a": "gpio",
    "zephyr_gpio_emul": "gpio",
    "zephyr_gpio_emul_sdl": "gpio",
    #
    # haptics
    "ti_drv2605": "haptics",
    #
    # hdlc_rcp_if
    "nxp_hdlc_rcp_if": "hdlc_rcp_if",
    "uart_hdlc_rcp_if": "hdlc_rcp_if",
    #
    # hwinfo
    "atmel_sam0_id": "hwinfo",
    "atmel_sam4l_uid": "hwinfo",
    "atmel_sam_rstc": "hwinfo",
    "cypress_psoc6_uid": "hwinfo",
    "litex_dna0": "hwinfo",
    "nxp_imx_src": "hwinfo",
    "nxp_imx_src_rev2": "hwinfo",
    "nxp_lpc_uid": "hwinfo",
    #
    # hwspinlock
    "sqn_hwspinlock": "hwspinlock",
    #
    # i2c
    "adi_max32_i2c": "i2c",
    "altr_nios2_i2c": "i2c",
    "ambiq_i2c": "i2c",
    "andestech_atciic100": "i2c",
    "arm_versatile_i2c": "i2c",
    "atmel_sam0_i2c": "i2c",
    "atmel_sam_i2c_twi": "i2c",
    "atmel_sam_i2c_twihs": "i2c",
    "atmel_sam_i2c_twim": "i2c",
    "brcm_iproc_i2c": "i2c",
    "ene_kb1200_i2c": "i2c",
    "espressif_esp32_i2c": "i2c",
    "fsl_imx21_i2c": "i2c",
    "gd_gd32_i2c": "i2c",
    "gpio_i2c": "i2c",
    "gpio_i2c_switch": "i2c",
    "infineon_cat1_i2c": "i2c",
    "infineon_xmc4xxx_i2c": "i2c",
    "intel_sedi_i2c": "i2c",
    "ite_enhance_i2c": "i2c",
    "ite_it8xxx2_i2c": "i2c",
    "litex_i2c": "i2c",
    "microchip_mpfs_i2c": "i2c",
    "microchip_xec_i2c": "i2c",
    "microchip_xec_i2c_v2": "i2c",
    "nordic_nrf_twis": "i2c",
    "nuvoton_npcx_i2c_ctrl": "i2c",
    "nuvoton_npcx_i2c_port": "i2c",
    "nuvoton_numaker_i2c": "i2c",
    "nxp_kinetis_i2c": "i2c",
    "nxp_lpc11u6x_i2c": "i2c",
    "nxp_lpc_i2c": "i2c",
    "nxp_lpi2c": "i2c",
    "nxp_sc18im704_i2c": "i2c",
    "openisa_rv32m1_lpi2c": "i2c",
    "renesas_ra_iic": "i2c",
    "renesas_rcar_i2c": "i2c",
    "renesas_smartbond_i2c": "i2c",
    "sifive_i2c0": "i2c",
    "silabs_gecko_i2c": "i2c",
    "st_stm32_i2c_v1": "i2c",
    "st_stm32_i2c_v2": "i2c",
    "telink_b91_i2c": "i2c",
    "ti_cc13xx_cc26xx_i2c": "i2c",
    "ti_cc32xx_i2c": "i2c",
    "ti_omap_i2c": "i2c",
    "ti_tca9544a": "i2c",
    "ti_tca9546a": "i2c",
    "ti_tca9548a": "i2c",
    "vnd_i2c": "i2c",
    "xlnx_xps_iic_2_00_a": "i2c",
    "xlnx_xps_iic_2_1": "i2c",
    "zephyr_i2c_emul_controller": "i2c",
    #
    # i2c/target
    "zephyr_i2c_target_eeprom": "i2c/target",
    #
    # i2s
    "atmel_sam_ssc": "i2s",
    "espressif_esp32_i2s": "i2s",
    "nxp_lpc_i2s": "i2s",
    "nxp_mcux_i2s": "i2s",
    "st_stm32_i2s": "i2s",
    "vnd_i2s": "i2s",
    #
    # i3c
    "cdns_i3c": "i3c",
    "nuvoton_npcx_i3c": "i3c",
    "nxp_mcux_i3c": "i3c",
    "st_stm32_i3c": "i3c",
    "vnd_i3c": "i3c",
    #
    # ieee802154
    "atmel_rf2xx": "ieee802154",
    "decawave_dw1000": "ieee802154",
    "nordic_nrf_ieee802154": "ieee802154",
    "nxp_kw41z_ieee802154": "ieee802154",
    "nxp_mcr20a": "ieee802154",
    "telink_b91_zb": "ieee802154",
    "ti_cc1200": "ieee802154",
    "ti_cc13xx_cc26xx_ieee802154": "ieee802154",
    "ti_cc13xx_cc26xx_ieee802154_subghz": "ieee802154",
    "ti_cc2520": "ieee802154",
    "zephyr_ieee802154_uart_pipe": "ieee802154",
    #
    # input
    "adc_keys": "input",
    "analog_axis": "input",
    "chipsemi_chsc6x": "input",
    "cirque_pinnacle": "input",
    "espressif_esp32_touch": "input",
    "focaltech_ft5336": "input",
    "futaba_sbus": "input",
    "goodix_gt911": "input",
    "gpio_kbd_matrix": "input",
    "gpio_keys": "input",
    "gpio_qdec": "input",
    "hynitron_cst816s": "input",
    "ilitek_ili2132a": "input",
    "ite_it8801_kbd": "input",
    "ite_it8xxx2_kbd": "input",
    "microchip_cap12xx": "input",
    "microchip_xec_kbd": "input",
    "nintendo_nunchuk": "input",
    "nuvoton_npcx_kbd": "input",
    "pixart_pat912x": "input",
    "pixart_paw32xx": "input",
    "pixart_pmw3610": "input",
    "sitronix_cf1133": "input",
    "st_stmpe811": "input",
    "xptek_xpt2046": "input",
    "zephyr_input_sdl_touch": "input",
    "zephyr_native_linux_evdev": "input",
    #
    # interrupt_controller
    "arm_gic_v1": "interrupt_controller",
    "arm_gic_v2": "interrupt_controller",
    "arm_gic_v3": "interrupt_controller",
    "arm_gic_v3_its": "interrupt_controller",
    "atmel_sam0_eic": "interrupt_controller",
    "gaisler_irqmp": "interrupt_controller",
    "gd_gd32_exti": "interrupt_controller",
    "infineon_xmc4xxx_intc": "interrupt_controller",
    "intel_ace_intc": "interrupt_controller",
    "intel_cavs_intc": "interrupt_controller",
    "intel_ioapic": "interrupt_controller",
    "intel_loapic": "interrupt_controller",
    "intel_vt_d": "interrupt_controller",
    "ite_it8xxx2_wuc": "interrupt_controller",
    "litex_vexriscv_intc0": "interrupt_controller",
    "mediatek_adsp_intc": "interrupt_controller",
    "microchip_xec_ecia": "interrupt_controller",
    "nuclei_eclic": "interrupt_controller",
    "nuvoton_npcx_miwu": "interrupt_controller",
    "nxp_irqsteer_intc": "interrupt_controller",
    "nxp_pint": "interrupt_controller",
    "nxp_s32_siul2_eirq": "interrupt_controller",
    "nxp_s32_wkpu": "interrupt_controller",
    "openisa_rv32m1_intmux": "interrupt_controller",
    "renesas_ra_interrupt_controller_unit": "interrupt_controller",
    "shared_irq": "interrupt_controller",
    "sifive_plic_1_0_0": "interrupt_controller",
    "snps_arcv2_intc": "interrupt_controller",
    "snps_designware_intc": "interrupt_controller",
    "st_stm32wb0_gpio_intc": "interrupt_controller",
    "swerv_pic": "interrupt_controller",
    "ti_vim": "interrupt_controller",
    "wch_pfic": "interrupt_controller",
    #
    # ipm
    "arm_mhu": "ipm",
    "espressif_esp32_ipm": "ipm",
    "intel_sedi_ipm": "ipm",
    "linaro_ivshmem_ipm": "ipm",
    "nordic_nrf_ipc": "ipm",
    "nxp_imx_mu": "ipm",
    "nxp_lpc_mailbox": "ipm",
    "st_stm32_hsem_mailbox": "ipm",
    "st_stm32_ipcc_mailbox": "ipm",
    "xlnx_zynqmp_ipi_mailbox": "ipm",
    "zephyr_mbox_ipm": "ipm",
    #
    # kscan
    "zephyr_kscan_input": "kscan",
    #
    # led
    "gpio_leds": "led",
    "holtek_ht16k33": "led",
    "issi_is31fl3194": "led",
    "issi_is31fl3216a": "led",
    "issi_is31fl3733": "led",
    "microchip_xec_bbled": "led",
    "nordic_npm1300_led": "led",
    "nxp_pca9633": "led",
    "onnn_ncp5623": "led",
    "pwm_leds": "led",
    "ti_lp3943": "led",
    "ti_lp5009": "led",
    "ti_lp5012": "led",
    "ti_lp5018": "led",
    "ti_lp5024": "led",
    "ti_lp5030": "led",
    "ti_lp5036": "led",
    "ti_lp5562": "led",
    "ti_lp5569": "led",
    "ti_tlc59108": "led",
    #
    # led_strip
    "apa_apa102": "led_strip",
    "greeled_lpd8803": "led_strip",
    "greeled_lpd8806": "led_strip",
    "ti_tlc5971": "led_strip",
    "ti_tlc59731": "led_strip",
    "worldsemi_ws2812_gpio": "led_strip",
    "worldsemi_ws2812_i2s": "led_strip",
    "worldsemi_ws2812_rpi_pico_pio": "led_strip",
    "worldsemi_ws2812_spi": "led_strip",
    #
    # lora
    "reyax_rylrxxx": "lora",
    "semtech_sx1272": "lora",
    "semtech_sx1276": "lora",
    #
    # mbox
    "andestech_mbox_plic_sw": "mbox",
    "espressif_mbox_esp32": "mbox",
    "linaro_ivshmem_mbox": "mbox",
    "nordic_mbox_nrf_ipc": "mbox",
    "nordic_nrf_bellboard_rx": "mbox",
    "nordic_nrf_bellboard_tx": "mbox",
    "nordic_nrf_vevif_event_rx": "mbox",
    "nordic_nrf_vevif_event_tx": "mbox",
    "nordic_nrf_vevif_task_rx": "mbox",
    "nordic_nrf_vevif_task_tx": "mbox",
    "nxp_mbox_imx_mu": "mbox",
    "nxp_mbox_mailbox": "mbox",
    "nxp_s32_mru": "mbox",
    "st_mbox_stm32_hsem": "mbox",
    #
    # mdio
    "adi_adin2111_mdio": "mdio",
    "atmel_sam_mdio": "mdio",
    "espressif_esp32_mdio": "mdio",
    "infineon_xmc4xxx_mdio": "mdio",
    "litex_liteeth_mdio": "mdio",
    "microchip_lan865x_mdio": "mdio",
    "nxp_enet_mdio": "mdio",
    "nxp_enet_qos_mdio": "mdio",
    "nxp_imx_netc_emdio": "mdio",
    "nxp_s32_gmac_mdio": "mdio",
    "nxp_s32_netc_emdio": "mdio",
    "renesas_ra_mdio": "mdio",
    "smsc_lan91c111_mdio": "mdio",
    "snps_dwcxgmac_mdio": "mdio",
    "st_stm32_mdio": "mdio",
    "zephyr_mdio_gpio": "mdio",
    #
    # memc
    "atmel_sam_smc": "memc",
    "mspi_aps6404l": "memc",
    "nxp_imx_flexspi": "memc",
    "nxp_imx_flexspi_s27ks0641": "memc",
    "nxp_imx_flexspi_w956a8mbya": "memc",
    "nxp_s32_qspi": "memc",
    "renesas_ra_sdram": "memc",
    "renesas_smartbond_nor_psram": "memc",
    "sifive_fu740_c000_ddr": "memc",
    "st_stm32_fmc": "memc",
    "st_stm32_fmc_nor_psram": "memc",
    "st_stm32_fmc_sdram": "memc",
    "st_stm32h7_fmc": "memc",
    #
    # mfd
    "adi_ad559x": "mfd",
    "adi_adp5585": "mfd",
    "adi_max22017": "mfd",
    "awinic_aw9523b": "mfd",
    "infineon_tle9104": "mfd",
    "ite_it8801_altctrl": "mfd",
    "ite_it8801_mfd": "mfd",
    "maxim_ds3231_mfd": "mfd",
    "maxim_max20335": "mfd",
    "maxim_max31790": "mfd",
    "nordic_npm1300": "mfd",
    "nordic_npm2100": "mfd",
    "nordic_npm6001": "mfd",
    "nuvoton_nct38xx": "mfd",
    "nxp_lp_flexcomm": "mfd",
    "rohm_bd8lb600fs": "mfd",
    "x_powers_axp192": "mfd",
    #
    # mipi_dbi
    "nxp_lcdic": "mipi_dbi",
    "nxp_mipi_dbi_flexio_lcdif": "mipi_dbi",
    "renesas_smartbond_mipi_dbi": "mipi_dbi",
    "st_stm32_fmc_mipi_dbi": "mipi_dbi",
    "zephyr_mipi_dbi_bitbang": "mipi_dbi",
    "zephyr_mipi_dbi_spi": "mipi_dbi",
    #
    # mipi_dsi
    "nxp_imx_mipi_dsi": "mipi_dsi",
    "nxp_mipi_dsi_2l": "mipi_dsi",
    "renesas_ra_mipi_dsi": "mipi_dsi",
    "st_stm32_mipi_dsi": "mipi_dsi",
    "vnd_mipi_dsi": "mipi_dsi",
    #
    # misc/devmux
    "zephyr_devmux": "misc/devmux",
    #
    # misc/ethos_u
    "arm_ethos_u": "misc/ethos_u",
    #
    # misc/ft8xx
    "ftdi_ft800": "misc/ft8xx",
    #
    # misc/grove_lcd_rgb
    "seeed_grove_lcd_rgb": "misc/grove_lcd_rgb",
    #
    # misc/mcux_flexio
    "nxp_flexio": "misc/mcux_flexio",
    #
    # misc/nordic_vpr_launcher
    "nordic_nrf_vpr_coprocessor": "misc/nordic_vpr_launcher",
    #
    # misc/nxp_s32_emios
    "nxp_s32_emios": "misc/nxp_s32_emios",
    #
    # misc/pio_rpi_pico
    "raspberrypi_pico_pio": "misc/pio_rpi_pico",
    #
    # misc/renesas_ra_external_interrupt
    "renesas_ra_external_interrupt": "misc/renesas_ra_external_interrupt",
    #
    # misc/timeaware_gpio
    "intel_timeaware_gpio": "misc/timeaware_gpio",
    #
    # mm
    "intel_adsp_tlb": "mm",
    #
    # modem
    "nordic_nrf91_slm": "modem",
    "quectel_bg95": "modem",
    "quectel_bg9x": "modem",
    "quectel_eg25_g": "modem",
    "simcom_sim7080": "modem",
    "sqn_gm02s": "modem",
    "swir_hl7800": "modem",
    "telit_me310g1": "modem",
    "telit_me910g1": "modem",
    "u_blox_lara_r6": "modem",
    "u_blox_sara_r4": "modem",
    "u_blox_sara_r5": "modem",
    "wnc_m14a2a": "modem",
    #
    # mspi
    "ambiq_mspi_controller": "mspi",
    "zephyr_mspi_emul_controller": "mspi",
    #
    # pcie/controller
    "brcm_brcmstb_pcie": "pcie/controller",
    #
    # pcie/endpoint
    "brcm_iproc_pcie_ep": "pcie/endpoint",
    #
    # pcie/host
    "pci_host_ecam_generic": "pcie/host",
    "pcie_controller": "pcie/host",
    "ptm_root": "pcie/host",
    #
    # peci
    "ite_it8xxx2_peci": "peci",
    "microchip_xec_peci": "peci",
    "nuvoton_npcx_peci": "peci",
    #
    # pinctrl
    "ene_kb1200_pinctrl": "pinctrl",
    "infineon_xmc4xxx_pinctrl": "pinctrl",
    "ite_it8xxx2_pinctrl_func": "pinctrl",
    "microchip_mec5_pinctrl": "pinctrl",
    "microchip_xec_pinctrl": "pinctrl",
    "nuvoton_numaker_pinctrl": "pinctrl",
    "nuvoton_numicro_pinctrl": "pinctrl",
    "nxp_port_pinmux": "pinctrl",
    "openisa_rv32m1_pinmux": "pinctrl",
    "quicklogic_eos_s3_pinctrl": "pinctrl",
    "realtek_rts5912_pinctrl": "pinctrl",
    "sensry_sy1xx_pinctrl": "pinctrl",
    "sifive_pinctrl": "pinctrl",
    "silabs_dbus_pinctrl": "pinctrl",
    "snps_emsdp_pinctrl": "pinctrl",
    "telink_b91_pinctrl": "pinctrl",
    "ti_cc13xx_cc26xx_pinctrl": "pinctrl",
    "ti_cc32xx_pinctrl": "pinctrl",
    "ti_k3_pinctrl": "pinctrl",
    "xlnx_pinctrl_zynq": "pinctrl",
    "xlnx_pinctrl_zynqmp": "pinctrl",
    #
    # pinctrl/renesas/rcar
    "renesas_rcar_pfc": "pinctrl/renesas/rcar",
    #
    # pinctrl/renesas/rz
    "renesas_rzt2m_pinctrl": "pinctrl/renesas/rz",
    #
    # pm_cpu_ops
    "arm_psci_0_2": "pm_cpu_ops",
    "arm_psci_1_1": "pm_cpu_ops",
    #
    # power_domain
    "intel_adsp_power_domain": "power_domain",
    "nxp_scu_pd": "power_domain",
    "power_domain_gpio": "power_domain",
    "power_domain_gpio_monitor": "power_domain",
    #
    # ps2
    "microchip_xec_ps2": "ps2",
    "nuvoton_npcx_ps2_channel": "ps2",
    "nuvoton_npcx_ps2_ctrl": "ps2",
    #
    # ptp_clock
    "nxp_enet_ptp_clock": "ptp_clock",
    #
    # pwm
    "adi_max32_pwm": "pwm",
    "atmel_sam0_tc_pwm": "pwm",
    "atmel_sam0_tcc_pwm": "pwm",
    "atmel_sam_pwm": "pwm",
    "ene_kb1200_pwm": "pwm",
    "espressif_esp32_ledc": "pwm",
    "espressif_esp32_mcpwm": "pwm",
    "fsl_imx27_pwm": "pwm",
    "gd_gd32_pwm": "pwm",
    "infineon_cat1_pwm": "pwm",
    "infineon_xmc4xxx_ccu4_pwm": "pwm",
    "infineon_xmc4xxx_ccu8_pwm": "pwm",
    "intel_blinky_pwm": "pwm",
    "ite_it8801_pwm": "pwm",
    "ite_it8xxx2_pwm": "pwm",
    "litex_pwm": "pwm",
    "maxim_max31790_pwm": "pwm",
    "microchip_xec_pwm": "pwm",
    "microchip_xec_pwmbbled": "pwm",
    "nordic_nrf_sw_pwm": "pwm",
    "nuvoton_npcx_pwm": "pwm",
    "nuvoton_numaker_pwm": "pwm",
    "nxp_ctimer_pwm": "pwm",
    "nxp_flexio_pwm": "pwm",
    "nxp_ftm_pwm": "pwm",
    "nxp_imx_pwm": "pwm",
    "nxp_kinetis_pwt": "pwm",
    "nxp_kinetis_tpm": "pwm",
    "nxp_pca9685_pwm": "pwm",
    "nxp_qtmr_pwm": "pwm",
    "nxp_s32_emios_pwm": "pwm",
    "nxp_sctimer_pwm": "pwm",
    "openisa_rv32m1_tpm": "pwm",
    "raspberrypi_pico_pwm": "pwm",
    "renesas_pwm_rcar": "pwm",
    "renesas_ra_pwm": "pwm",
    "sifive_pwm0": "pwm",
    "silabs_gecko_pwm": "pwm",
    "st_stm32_pwm": "pwm",
    "telink_b91_pwm": "pwm",
    "ti_cc13xx_cc26xx_timer_pwm": "pwm",
    "vnd_pwm": "pwm",
    "xlnx_xps_timer_1_00_a_pwm": "pwm",
    "zephyr_fake_pwm": "pwm",
    #
    # regulator
    "adi_adp5360_regulator": "regulator",
    "cirrus_cp9314": "regulator",
    "maxim_max20335_regulator": "regulator",
    "mps_mpm54304": "regulator",
    "nordic_npm1100": "regulator",
    "nordic_npm1300_regulator": "regulator",
    "nordic_npm2100_regulator": "regulator",
    "nordic_npm6001_regulator": "regulator",
    "nxp_pca9420": "regulator",
    "nxp_vref": "regulator",
    "raspberrypi_core_supply_regulator": "regulator",
    "regulator_fixed": "regulator",
    "regulator_gpio": "regulator",
    "renesas_smartbond_regulator": "regulator",
    "x_powers_axp192_regulator": "regulator",
    "zephyr_fake_regulator": "regulator",
    #
    # reset
    "aspeed_ast10x0_reset": "reset",
    "gd_gd32_rctl": "reset",
    "intel_socfpga_reset": "reset",
    "nuvoton_npcx_rst": "reset",
    "nuvoton_numaker_rst": "reset",
    "nxp_lpc_syscon_reset": "reset",
    "nxp_rstctl": "reset",
    "raspberrypi_pico_reset": "reset",
    "st_stm32_rcc_rctl": "reset",
    #
    # retained_mem
    "nordic_nrf_gpregret": "retained_mem",
    "zephyr_retained_ram": "retained_mem",
    "zephyr_retained_reg": "retained_mem",
    #
    # rtc
    "ambiq_am1805": "rtc",
    "ambiq_rtc": "rtc",
    "atmel_sam_rtc": "rtc",
    "infineon_cat1_rtc": "rtc",
    "infineon_xmc4xxx_rtc": "rtc",
    "maxim_ds1307": "rtc",
    "maxim_ds3231_rtc": "rtc",
    "microcrystal_rv3028": "rtc",
    "microcrystal_rv8803": "rtc",
    "microcrystal_rv_8263_c8": "rtc",
    "motorola_mc146818": "rtc",
    "nuvoton_numaker_rtc": "rtc",
    "nxp_irtc": "rtc",
    "nxp_pcf8523": "rtc",
    "nxp_pcf8563": "rtc",
    "raspberrypi_pico_rtc": "rtc",
    "renesas_smartbond_rtc": "rtc",
    "st_stm32_rtc": "rtc",
    "zephyr_fake_rtc": "rtc",
    "zephyr_rtc_emul": "rtc",
    #
    # sdhc
    "atmel_sam_hsmci": "sdhc",
    "cdns_sdhc": "sdhc",
    "espressif_esp32_sdhc_slot": "sdhc",
    "infineon_cat1_sdhc_sdio": "sdhc",
    "intel_emmc_host": "sdhc",
    "nxp_imx_usdhc": "sdhc",
    "nxp_lpc_sdif": "sdhc",
    "renesas_ra_sdhc": "sdhc",
    "renesas_rcar_mmc": "sdhc",
    "zephyr_sdhc_spi_slot": "sdhc",
    #
    # sensor/a01nyub
    "dfrobot_a01nyub": "sensor/a01nyub",
    #
    # sensor/adi/adltc2990
    "adi_adltc2990": "sensor/adi/adltc2990",
    #
    # sensor/adi/adt7310
    "adi_adt7310": "sensor/adi/adt7310",
    #
    # sensor/adi/adt7420
    "adi_adt7420": "sensor/adi/adt7420",
    #
    # sensor/adi/adxl345
    "adi_adxl345": "sensor/adi/adxl345",
    #
    # sensor/adi/adxl362
    "adi_adxl362": "sensor/adi/adxl362",
    #
    # sensor/adi/adxl367
    "adi_adxl366": "sensor/adi/adxl367",
    "adi_adxl367": "sensor/adi/adxl367",
    #
    # sensor/adi/adxl372
    "adi_adxl372": "sensor/adi/adxl372",
    #
    # sensor/amd_sb_tsi
    "amd_sb_tsi": "sensor/amd_sb_tsi",
    #
    # sensor/amg88xx
    "panasonic_amg88xx": "sensor/amg88xx",
    #
    # sensor/ams/ams_as5600
    "ams_as5600": "sensor/ams/ams_as5600",
    #
    # sensor/ams/ams_iAQcore
    "ams_iaqcore": "sensor/ams/ams_iAQcore",
    #
    # sensor/ams/ccs811
    "ams_ccs811": "sensor/ams/ccs811",
    #
    # sensor/ams/ens210
    "ams_ens210": "sensor/ams/ens210",
    #
    # sensor/ams/tcs3400
    "ams_tcs3400": "sensor/ams/tcs3400",
    #
    # sensor/ams/tmd2620
    "ams_tmd2620": "sensor/ams/tmd2620",
    #
    # sensor/ams/tsl2540
    "ams_tsl2540": "sensor/ams/tsl2540",
    #
    # sensor/ams/tsl2561
    "ams_tsl2561": "sensor/ams/tsl2561",
    #
    # sensor/ams/tsl2591
    "ams_tsl2591": "sensor/ams/tsl2591",
    #
    # sensor/aosong/ags10
    "aosong_ags10": "sensor/aosong/ags10",
    #
    # sensor/aosong/dht
    "aosong_dht": "sensor/aosong/dht",
    #
    # sensor/aosong/dht20
    "aosong_aht20": "sensor/aosong/dht20",
    "aosong_am2301b": "sensor/aosong/dht20",
    "aosong_dht20": "sensor/aosong/dht20",
    #
    # sensor/apds9253
    "avago_apds9253": "sensor/apds9253",
    #
    # sensor/apds9306
    "avago_apds9306": "sensor/apds9306",
    #
    # sensor/apds9960
    "avago_apds9960": "sensor/apds9960",
    #
    # sensor/asahi_kasei/ak8975
    "asahi_kasei_ak8975": "sensor/asahi_kasei/ak8975",
    #
    # sensor/asahi_kasei/akm09918c
    "asahi_kasei_akm09918c": "sensor/asahi_kasei/akm09918c",
    #
    # sensor/bosch/bma280
    "bosch_bma280": "sensor/bosch/bma280",
    #
    # sensor/bosch/bma4xx
    "bosch_bma4xx": "sensor/bosch/bma4xx",
    #
    # sensor/bosch/bmc150_magn
    "bosch_bmc150_magn": "sensor/bosch/bmc150_magn",
    #
    # sensor/bosch/bmg160
    "bosch_bmg160": "sensor/bosch/bmg160",
    #
    # sensor/bosch/bmi08x
    "bosch_bmi08x_accel": "sensor/bosch/bmi08x",
    "bosch_bmi08x_gyro": "sensor/bosch/bmi08x",
    #
    # sensor/bosch/bmi160
    "bosch_bmi160": "sensor/bosch/bmi160",
    #
    # sensor/bosch/bmi270
    "bosch_bmi270": "sensor/bosch/bmi270",
    #
    # sensor/bosch/bmi323
    "bosch_bmi323": "sensor/bosch/bmi323",
    #
    # sensor/bosch/bmp180
    "bosch_bmp180": "sensor/bosch/bmp180",
    #
    # sensor/bosch/bmp388
    "bosch_bmp388": "sensor/bosch/bmp388",
    "bosch_bmp390": "sensor/bosch/bmp388",
    #
    # sensor/current_amp
    "current_sense_amplifier": "sensor/current_amp",
    #
    # sensor/ene_tach_kb1200
    "ene_kb1200_tach": "sensor/ene_tach_kb1200",
    #
    # sensor/ens160
    "sciosense_ens160": "sensor/ens160",
    #
    # sensor/espressif/esp32_temp
    "espressif_esp32_temp": "sensor/espressif/esp32_temp",
    #
    # sensor/espressif/pcnt_esp32
    "espressif_esp32_pcnt": "sensor/espressif/pcnt_esp32",
    #
    # sensor/explorir_m
    "gss_explorir_m": "sensor/explorir_m",
    #
    # sensor/f75303
    "fintek_f75303": "sensor/f75303",
    #
    # sensor/fcx_mldx5
    "ap_fcx_mldx5": "sensor/fcx_mldx5",
    #
    # sensor/grow_r502a
    "hzgrow_r502a": "sensor/grow_r502a",
    "hzgrow_r502a_led": "sensor/grow_r502a",
    #
    # sensor/hc_sr04
    "hc_sr04": "sensor/hc_sr04",
    #
    # sensor/honeywell/hmc5883l
    "honeywell_hmc5883l": "sensor/honeywell/hmc5883l",
    #
    # sensor/honeywell/mpr
    "honeywell_mpr": "sensor/honeywell/mpr",
    #
    # sensor/honeywell/sm351lt
    "honeywell_sm351lt": "sensor/honeywell/sm351lt",
    #
    # sensor/hp206c
    "hoperf_hp206c": "sensor/hp206c",
    #
    # sensor/infineon/dps310
    "infineon_dps310": "sensor/infineon/dps310",
    #
    # sensor/infineon/tle9104
    "infineon_tle9104_diagnostics": "sensor/infineon/tle9104",
    #
    # sensor/infineon/xmc4xxx_temp
    "infineon_xmc4xxx_temp": "sensor/infineon/xmc4xxx_temp",
    #
    # sensor/ite/ite_tach_it8xxx2
    "ite_it8xxx2_tach": "sensor/ite/ite_tach_it8xxx2",
    #
    # sensor/ite/ite_vcmp_it8xxx2
    "ite_it8xxx2_vcmp": "sensor/ite/ite_vcmp_it8xxx2",
    #
    # sensor/jedec/jc42
    "jedec_jc_42_4_temp": "sensor/jedec/jc42",
    #
    # sensor/lm35
    "lm35": "sensor/lm35",
    #
    # sensor/lm75
    "lm75": "sensor/lm75",
    #
    # sensor/lm77
    "lm77": "sensor/lm77",
    #
    # sensor/ltrf216a
    "ltr_f216a": "sensor/ltrf216a",
    #
    # sensor/maxim/ds18b20
    "maxim_ds18b20": "sensor/maxim/ds18b20",
    "maxim_ds18s20": "sensor/maxim/ds18b20",
    #
    # sensor/maxim/ds3231
    "maxim_ds3231_sensor": "sensor/maxim/ds3231",
    #
    # sensor/maxim/max17055
    "maxim_max17055": "sensor/maxim/max17055",
    #
    # sensor/maxim/max17262
    "maxim_max17262": "sensor/maxim/max17262",
    #
    # sensor/maxim/max30101
    "maxim_max30101": "sensor/maxim/max30101",
    #
    # sensor/maxim/max31790
    "maxim_max31790_fan_fault": "sensor/maxim/max31790",
    "maxim_max31790_fan_speed": "sensor/maxim/max31790",
    #
    # sensor/maxim/max31855
    "maxim_max31855": "sensor/maxim/max31855",
    #
    # sensor/maxim/max31875
    "maxim_max31875": "sensor/maxim/max31875",
    #
    # sensor/maxim/max44009
    "maxim_max44009": "sensor/maxim/max44009",
    #
    # sensor/maxim/max6675
    "maxim_max6675": "sensor/maxim/max6675",
    #
    # sensor/meas/ms5607
    "meas_ms5607": "sensor/meas/ms5607",
    #
    # sensor/meas/ms5837
    "meas_ms5837": "sensor/meas/ms5837",
    #
    # sensor/melexis/mlx90394
    "melexis_mlx90394": "sensor/melexis/mlx90394",
    #
    # sensor/memsic/mc3419
    "memsic_mc3419": "sensor/memsic/mc3419",
    #
    # sensor/mhz19b
    "winsen_mhz19b": "sensor/mhz19b",
    #
    # sensor/microchip/mchp_tach_xec
    "microchip_xec_tach": "sensor/microchip/mchp_tach_xec",
    #
    # sensor/microchip/mcp9600
    "microchip_mcp9600": "sensor/microchip/mcp9600",
    #
    # sensor/microchip/mcp970x
    "microchip_mcp970x": "sensor/microchip/mcp970x",
    #
    # sensor/microchip/tcn75a
    "microchip_tcn75a": "sensor/microchip/tcn75a",
    #
    # sensor/nct75
    "onnn_nct75": "sensor/nct75",
    #
    # sensor/nordic/npm1300_charger
    "nordic_npm1300_charger": "sensor/nordic/npm1300_charger",
    #
    # sensor/nordic/npm2100_vbat
    "nordic_npm2100_vbat": "sensor/nordic/npm2100_vbat",
    #
    # sensor/nordic/qdec_nrfx
    "nordic_nrf_qdec": "sensor/nordic/qdec_nrfx",
    #
    # sensor/nordic/temp
    "nordic_nrf_temp": "sensor/nordic/temp",
    "nordic_nrf_temp_nrfs": "sensor/nordic/temp",
    #
    # sensor/ntc_thermistor
    "epcos_b57861s0103a039": "sensor/ntc_thermistor",
    "murata_ncp15wb473": "sensor/ntc_thermistor",
    "murata_ncp15xh103": "sensor/ntc_thermistor",
    "ntc_thermistor_generic": "sensor/ntc_thermistor",
    "tdk_ntcg163jf103ft1": "sensor/ntc_thermistor",
    #
    # sensor/nuvoton/nuvoton_adc_cmp_npcx
    "nuvoton_adc_cmp": "sensor/nuvoton/nuvoton_adc_cmp_npcx",
    #
    # sensor/nuvoton/nuvoton_tach_npcx
    "nuvoton_npcx_tach": "sensor/nuvoton/nuvoton_tach_npcx",
    #
    # sensor/nxp/fxas21002
    "nxp_fxas21002": "sensor/nxp/fxas21002",
    #
    # sensor/nxp/fxls8974
    "nxp_fxls8974": "sensor/nxp/fxls8974",
    #
    # sensor/nxp/fxos8700
    "nxp_fxos8700": "sensor/nxp/fxos8700",
    #
    # sensor/nxp/mcux_acmp
    "nxp_kinetis_acmp": "sensor/nxp/mcux_acmp",
    #
    # sensor/nxp/mcux_lpcmp
    "nxp_lpcmp": "sensor/nxp/mcux_lpcmp",
    #
    # sensor/nxp/nxp_kinetis_temp
    "nxp_kinetis_temperature": "sensor/nxp/nxp_kinetis_temp",
    #
    # sensor/nxp/nxp_tempmon
    "nxp_tempmon": "sensor/nxp/nxp_tempmon",
    #
    # sensor/nxp/p3t1755
    "nxp_p3t1755": "sensor/nxp/p3t1755",
    #
    # sensor/nxp/qdec_mcux
    "nxp_mcux_qdec": "sensor/nxp/qdec_mcux",
    #
    # sensor/nxp/qdec_nxp_s32
    "nxp_qdec_s32": "sensor/nxp/qdec_nxp_s32",
    #
    # sensor/pms7003
    "plantower_pms7003": "sensor/pms7003",
    #
    # sensor/qdec_sam
    "atmel_sam_tc_qdec": "sensor/qdec_sam",
    #
    # sensor/renesas/hs300x
    "renesas_hs300x": "sensor/renesas/hs300x",
    #
    # sensor/renesas/hs400x
    "renesas_hs400x": "sensor/renesas/hs400x",
    #
    # sensor/renesas/isl29035
    "isil_isl29035": "sensor/renesas/isl29035",
    #
    # sensor/rohm/bd8lb600fs
    "rohm_bd8lb600fs_diagnostics": "sensor/rohm/bd8lb600fs",
    #
    # sensor/rohm/bh1750
    "rohm_bh1750": "sensor/rohm/bh1750",
    #
    # sensor/rpi_pico_temp
    "raspberrypi_pico_temp": "sensor/rpi_pico_temp",
    #
    # sensor/s11059
    "hamamatsu_s11059": "sensor/s11059",
    #
    # sensor/seeed/grove
    "seeed_grove_light": "sensor/seeed/grove",
    "seeed_grove_temperature": "sensor/seeed/grove",
    #
    # sensor/seeed/hm330x
    "seeed_hm330x": "sensor/seeed/hm330x",
    #
    # sensor/sensirion/scd4x
    "sensirion_scd40": "sensor/sensirion/scd4x",
    "sensirion_scd41": "sensor/sensirion/scd4x",
    #
    # sensor/sensirion/sgp40
    "sensirion_sgp40": "sensor/sensirion/sgp40",
    #
    # sensor/sensirion/sht3xd
    "sensirion_sht3xd": "sensor/sensirion/sht3xd",
    #
    # sensor/sensirion/sht4x
    "sensirion_sht4x": "sensor/sensirion/sht4x",
    #
    # sensor/sensirion/shtcx
    "sensirion_shtcx": "sensor/sensirion/shtcx",
    #
    # sensor/sensirion/sts4x
    "sensirion_sts4x": "sensor/sensirion/sts4x",
    #
    # sensor/silabs/si7006
    "sensirion_sht21": "sensor/silabs/si7006",
    "silabs_si7006": "sensor/silabs/si7006",
    #
    # sensor/silabs/si7055
    "silabs_si7055": "sensor/silabs/si7055",
    #
    # sensor/silabs/si7060
    "silabs_si7060": "sensor/silabs/si7060",
    #
    # sensor/silabs/si7210
    "silabs_si7210": "sensor/silabs/si7210",
    #
    # sensor/st/hts221
    "st_hts221": "sensor/st/hts221",
    #
    # sensor/st/i3g4250d
    "st_i3g4250d": "sensor/st/i3g4250d",
    #
    # sensor/st/iis2dh
    "st_iis2dh": "sensor/st/iis2dh",
    #
    # sensor/st/iis2dlpc
    "st_iis2dlpc": "sensor/st/iis2dlpc",
    #
    # sensor/st/iis2iclx
    "st_iis2iclx": "sensor/st/iis2iclx",
    #
    # sensor/st/iis2mdc
    "st_iis2mdc": "sensor/st/iis2mdc",
    #
    # sensor/st/iis328dq
    "st_iis328dq": "sensor/st/iis328dq",
    #
    # sensor/st/iis3dhhc
    "st_iis3dhhc": "sensor/st/iis3dhhc",
    #
    # sensor/st/ism330dhcx
    "st_ism330dhcx": "sensor/st/ism330dhcx",
    #
    # sensor/st/lis2de12
    "st_lis2de12": "sensor/st/lis2de12",
    #
    # sensor/st/lis2dh
    "st_lis2dh": "sensor/st/lis2dh",
    #
    # sensor/st/lis2ds12
    "st_lis2ds12": "sensor/st/lis2ds12",
    #
    # sensor/st/lis2du12
    "st_lis2du12": "sensor/st/lis2du12",
    #
    # sensor/st/lis2dux12
    "st_lis2dux12": "sensor/st/lis2dux12",
    "st_lis2duxs12": "sensor/st/lis2dux12",
    #
    # sensor/st/lis2dw12
    "st_lis2dw12": "sensor/st/lis2dw12",
    #
    # sensor/st/lis2mdl
    "st_lis2mdl": "sensor/st/lis2mdl",
    #
    # sensor/st/lis3mdl
    "st_lis3mdl_magn": "sensor/st/lis3mdl",
    #
    # sensor/st/lps22hb
    "st_lps22hb_press": "sensor/st/lps22hb",
    #
    # sensor/st/lps22hh
    "st_lps22hh": "sensor/st/lps22hh",
    #
    # sensor/st/lps25hb
    "st_lps25hb_press": "sensor/st/lps25hb",
    #
    # sensor/st/lps2xdf
    "st_ilps22qs": "sensor/st/lps2xdf",
    "st_lps22df": "sensor/st/lps2xdf",
    "st_lps28dfw": "sensor/st/lps2xdf",
    #
    # sensor/st/lsm303dlhc_magn
    "st_lsm303dlhc_magn": "sensor/st/lsm303dlhc_magn",
    #
    # sensor/st/lsm6ds0
    "st_lsm6ds0": "sensor/st/lsm6ds0",
    #
    # sensor/st/lsm6dsl
    "st_lsm6dsl": "sensor/st/lsm6dsl",
    #
    # sensor/st/lsm6dso
    "st_lsm6dso": "sensor/st/lsm6dso",
    "st_lsm6dso32": "sensor/st/lsm6dso",
    #
    # sensor/st/lsm6dso16is
    "st_lsm6dso16is": "sensor/st/lsm6dso16is",
    #
    # sensor/st/lsm6dsv16x
    "st_lsm6dsv16x": "sensor/st/lsm6dsv16x",
    #
    # sensor/st/lsm9ds0_gyro
    "st_lsm9ds0_gyro": "sensor/st/lsm9ds0_gyro",
    #
    # sensor/st/lsm9ds0_mfd
    "st_lsm9ds0_mfd": "sensor/st/lsm9ds0_mfd",
    #
    # sensor/st/lsm9ds1
    "st_lsm9ds1": "sensor/st/lsm9ds1",
    #
    # sensor/st/qdec_stm32
    "st_stm32_qdec": "sensor/st/qdec_stm32",
    #
    # sensor/st/stm32_digi_temp
    "st_stm32_digi_temp": "sensor/st/stm32_digi_temp",
    #
    # sensor/st/stm32_temp
    "st_stm32_temp": "sensor/st/stm32_temp",
    "st_stm32_temp_cal": "sensor/st/stm32_temp",
    "st_stm32c0_temp_cal": "sensor/st/stm32_temp",
    #
    # sensor/st/stm32_vbat
    "st_stm32_vbat": "sensor/st/stm32_vbat",
    #
    # sensor/st/stm32_vref
    "st_stm32_vref": "sensor/st/stm32_vref",
    #
    # sensor/st/stts22h
    "st_stts22h": "sensor/st/stts22h",
    #
    # sensor/st/stts751
    "st_stts751": "sensor/st/stts751",
    #
    # sensor/st/vl53l0x
    "st_vl53l0x": "sensor/st/vl53l0x",
    #
    # sensor/st/vl53l1x
    "st_vl53l1x": "sensor/st/vl53l1x",
    #
    # sensor/sx9500
    "semtech_sx9500": "sensor/sx9500",
    #
    # sensor/tdk/icm42605
    "invensense_icm42605": "sensor/tdk/icm42605",
    #
    # sensor/tdk/icm42670
    "invensense_icm42670p": "sensor/tdk/icm42670",
    "invensense_icm42670s": "sensor/tdk/icm42670",
    #
    # sensor/tdk/icm42688
    "invensense_icm42688": "sensor/tdk/icm42688",
    #
    # sensor/tdk/icp10125
    "invensense_icp10125": "sensor/tdk/icp10125",
    #
    # sensor/tdk/mpu6050
    "invensense_mpu6050": "sensor/tdk/mpu6050",
    #
    # sensor/tdk/mpu9250
    "invensense_mpu9250": "sensor/tdk/mpu9250",
    #
    # sensor/th02
    "hoperf_th02": "sensor/th02",
    #
    # sensor/ti/bq274xx
    "ti_bq274xx": "sensor/ti/bq274xx",
    #
    # sensor/ti/fdc2x1x
    "ti_fdc2x1x": "sensor/ti/fdc2x1x",
    #
    # sensor/ti/ina219
    "ti_ina219": "sensor/ti/ina219",
    #
    # sensor/ti/ina226
    "ti_ina226": "sensor/ti/ina226",
    #
    # sensor/ti/ina23x
    "ti_ina230": "sensor/ti/ina23x",
    "ti_ina236": "sensor/ti/ina23x",
    "ti_ina237": "sensor/ti/ina23x",
    #
    # sensor/ti/ina3221
    "ti_ina3221": "sensor/ti/ina3221",
    #
    # sensor/ti/lm95234
    "national_lm95234": "sensor/ti/lm95234",
    #
    # sensor/ti/opt3001
    "ti_opt3001": "sensor/ti/opt3001",
    #
    # sensor/ti/ti_hdc
    "ti_hdc": "sensor/ti/ti_hdc",
    #
    # sensor/ti/tmag5170
    "ti_tmag5170": "sensor/ti/tmag5170",
    #
    # sensor/ti/tmp007
    "ti_tmp007": "sensor/ti/tmp007",
    #
    # sensor/ti/tmp1075
    "ti_tmp1075": "sensor/ti/tmp1075",
    #
    # sensor/ti/tmp108
    "ams_as6212": "sensor/ti/tmp108",
    "ti_tmp108": "sensor/ti/tmp108",
    #
    # sensor/ti/tmp112
    "ti_tmp112": "sensor/ti/tmp112",
    #
    # sensor/ti/tmp114
    "ti_tmp114": "sensor/ti/tmp114",
    #
    # sensor/ti/tmp116
    "ti_tmp116": "sensor/ti/tmp116",
    #
    # sensor/tsic_xx6
    "ist_tsic_xx6": "sensor/tsic_xx6",
    #
    # sensor/veaa_x_3
    "festo_veaa_x_3": "sensor/veaa_x_3",
    #
    # sensor/vishay/vcnl36825t
    "vishay_vcnl36825t": "sensor/vishay/vcnl36825t",
    #
    # sensor/vishay/vcnl4040
    "vishay_vcnl4040": "sensor/vishay/vcnl4040",
    #
    # sensor/vishay/veml7700
    "vishay_veml7700": "sensor/vishay/veml7700",
    #
    # sensor/voltage_divider
    "voltage_divider": "sensor/voltage_divider",
    #
    # sensor/wsen/wsen_hids_2525020210002
    "we_wsen_hids_2525020210002": "sensor/wsen/wsen_hids_2525020210002",
    #
    # sensor/wsen/wsen_pdus_25131308XXXXX
    "we_wsen_pdus_25131308xxxxx": "sensor/wsen/wsen_pdus_25131308XXXXX",
    #
    # serial
    "SBSA_COMPAT": "serial",
    "adi_max32_uart": "serial",
    "altr_jtag_uart": "serial",
    "altr_uart": "serial",
    "arm_cmsdk_uart": "serial",
    "arm_pl011": "serial",
    "atmel_sam0_uart": "serial",
    "atmel_sam_uart": "serial",
    "atmel_sam_usart": "serial",
    "brcm_bcm2711_aux_uart": "serial",
    "cdns_uart": "serial",
    "cypress_psoc6_uart": "serial",
    "efinix_sapphire_uart0": "serial",
    "ene_kb1200_uart": "serial",
    "espressif_esp32_uart": "serial",
    "espressif_esp32_usb_serial": "serial",
    "gaisler_apbuart": "serial",
    "gd_gd32_usart": "serial",
    "infineon_cat1_uart": "serial",
    "infineon_xmc4xxx_uart": "serial",
    "intel_lw_uart": "serial",
    "intel_sedi_uart": "serial",
    "ite_it8xxx2_uart": "serial",
    "litex_uart": "serial",
    "lowrisc_opentitan_uart": "serial",
    "microchip_coreuart": "serial",
    "microchip_mec5_uart": "serial",
    "microchip_xec_uart": "serial",
    "neorv32_uart": "serial",
    "nordic_nrf_uart": "serial",
    "ns16550": "serial",
    "nuvoton_npcx_uart": "serial",
    "nuvoton_numaker_uart": "serial",
    "nuvoton_numicro_uart": "serial",
    "nxp_imx_iuart": "serial",
    "nxp_imx_uart": "serial",
    "nxp_kinetis_lpsci": "serial",
    "nxp_kinetis_uart": "serial",
    "nxp_lpc11u6x_uart": "serial",
    "nxp_lpc_usart": "serial",
    "nxp_lpuart": "serial",
    "nxp_s32_linflexd": "serial",
    "openisa_rv32m1_lpuart": "serial",
    "quicklogic_usbserialport_s3b": "serial",
    "raspberrypi_pico_uart_pio": "serial",
    "realtek_rts5912_uart": "serial",
    "renesas_ra8_uart_sci_b": "serial",
    "renesas_ra_sci_uart": "serial",
    "renesas_ra_uart_sci": "serial",
    "renesas_rcar_hscif": "serial",
    "renesas_rcar_scif": "serial",
    "renesas_rz_scif_uart": "serial",
    "renesas_rzt2m_uart": "serial",
    "renesas_smartbond_uart": "serial",
    "segger_rtt_uart": "serial",
    "sensry_sy1xx_uart": "serial",
    "sifive_uart0": "serial",
    "silabs_eusart_uart": "serial",
    "silabs_gecko_leuart": "serial",
    "silabs_gecko_uart": "serial",
    "silabs_gecko_usart": "serial",
    "silabs_si32_usart": "serial",
    "snps_hostlink_uart": "serial",
    "st_stm32_uart": "serial",
    "telink_b91_uart": "serial",
    "ti_cc13xx_cc26xx_uart": "serial",
    "ti_cc32xx_uart": "serial",
    "ti_msp432p4xx_uart": "serial",
    "ti_stellaris_uart": "serial",
    "vnd_serial": "serial",
    "wch_usart": "serial",
    "xen_hvc_consoleio": "serial",
    "xlnx_xps_uartlite_1_00_a": "serial",
    "xlnx_xuartps": "serial",
    "zephyr_native_posix_uart": "serial",
    "zephyr_native_tty_uart": "serial",
    "zephyr_nus_uart": "serial",
    "zephyr_uart_emul": "serial",
    #
    # sip_svc
    "intel_socfpga_agilex_sip_smc": "sip_svc",
    #
    # smbus
    "intel_pch_smbus": "smbus",
    "st_stm32_smbus": "smbus",
    #
    # spi
    "adi_max32_spi": "spi",
    "ambiq_spi": "spi",
    "ambiq_spi_bleif": "spi",
    "ambiq_spid": "spi",
    "andestech_atcspi200": "spi",
    "arm_pl022": "spi",
    "atmel_sam0_spi": "spi",
    "atmel_sam_spi": "spi",
    "cypress_psoc6_spi": "spi",
    "espressif_esp32_spi": "spi",
    "gaisler_spimctrl": "spi",
    "gd_gd32_spi": "spi",
    "infineon_cat1_spi": "spi",
    "infineon_xmc4xxx_spi": "spi",
    "intel_penwell_spi": "spi",
    "intel_sedi_spi": "spi",
    "ite_it8xxx2_spi": "spi",
    "litex_spi": "spi",
    "litex_spi_litespi": "spi",
    "lowrisc_opentitan_spi": "spi",
    "microchip_mpfs_qspi": "spi",
    "microchip_mpfs_spi": "spi",
    "microchip_xec_qmspi": "spi",
    "microchip_xec_qmspi_ldma": "spi",
    "nuvoton_npcx_spip": "spi",
    "nuvoton_numaker_spi": "spi",
    "nxp_dspi": "spi",
    "nxp_flexio_spi": "spi",
    "nxp_imx_ecspi": "spi",
    "nxp_lpc_spi": "spi",
    "nxp_s32_spi": "spi",
    "opencores_spi_simple": "spi",
    "openisa_rv32m1_lpspi": "spi",
    "raspberrypi_pico_spi_pio": "spi",
    "renesas_ra8_spi_b": "spi",
    "renesas_ra_spi": "spi",
    "renesas_smartbond_spi": "spi",
    "sifive_spi0": "spi",
    "silabs_eusart_spi": "spi",
    "silabs_usart_spi": "spi",
    "snps_designware_spi": "spi",
    "st_stm32_spi": "spi",
    "telink_b91_spi": "spi",
    "ti_cc13xx_cc26xx_spi": "spi",
    "vnd_spi": "spi",
    "xlnx_xps_spi_2_00_a": "spi",
    "zephyr_spi_bitbang": "spi",
    "zephyr_spi_emul_controller": "spi",
    #
    # spi/spi_nxp_lpspi
    "nxp_lpspi": "spi/spi_nxp_lpspi",
    #
    # stepper
    "zephyr_fake_stepper": "stepper",
    "zephyr_gpio_stepper": "stepper",
    #
    # stepper/adi_tmc
    "adi_tmc2209": "stepper/adi_tmc",
    "adi_tmc5041": "stepper/adi_tmc",
    #
    # stepper/ti
    "ti_drv8424": "stepper/ti",
    #
    # syscon
    "syscon": "syscon",
    #
    # tee/optee
    "linaro_optee_tz": "tee/optee",
    #
    # timer
    "ambiq_stimer": "timer",
    "andestech_machine_timer": "timer",
    "atmel_sam0_rtc": "timer",
    "gaisler_gptimer": "timer",
    "intel_adsp_timer": "timer",
    "intel_hpet": "timer",
    "ite_it8xxx2_timer": "timer",
    "litex_timer0": "timer",
    "lowrisc_machine_timer": "timer",
    "microchip_mec5_ktimer": "timer",
    "microchip_xec_rtos_timer": "timer",
    "neorv32_machine_timer": "timer",
    "niosv_machine_timer": "timer",
    "nuclei_systimer": "timer",
    "nuvoton_npcx_itim_timer": "timer",
    "nxp_gpt_hw_timer": "timer",
    "nxp_kinetis_lptmr": "timer",
    "nxp_lptmr": "timer",
    "nxp_os_timer": "timer",
    "openisa_rv32m1_lptmr": "timer",
    "realtek_rts5912_rtmr": "timer",
    "renesas_rcar_cmt": "timer",
    "scr_machine_timer": "timer",
    "sifive_clint0": "timer",
    "silabs_gecko_burtc": "timer",
    "st_stm32_lptim": "timer",
    "sy1xx_sys_timer": "timer",
    "telink_machine_timer": "timer",
    "ti_am654_timer": "timer",
    "ti_cc13xx_cc26xx_rtc_timer": "timer",
    "wch_systick": "timer",
    "xlnx_ttcps": "timer",
    #
    # usb/bc12
    "diodes_pi3usb9201": "usb/bc12",
    #
    # usb/device
    "atmel_sam0_usb": "usb/device",
    "atmel_sam_usbc": "usb/device",
    "atmel_sam_usbhs": "usb/device",
    #
    # usb/udc
    "ambiq_usb": "usb/udc",
    "ite_it82xx2_usb": "usb/udc",
    "nordic_nrf_usbd": "usb/udc",
    "nuvoton_numaker_usbd": "usb/udc",
    "nxp_ehci": "usb/udc",
    "nxp_kinetis_usbd": "usb/udc",
    "nxp_lpcip3511": "usb/udc",
    "raspberrypi_pico_usbd": "usb/udc",
    "renesas_ra_udc": "usb/udc",
    "renesas_smartbond_usbd": "usb/udc",
    "snps_dwc2": "usb/udc",
    "st_stm32_otgfs": "usb/udc",
    "st_stm32_otghs": "usb/udc",
    "st_stm32_usb": "usb/udc",
    "zephyr_udc_skeleton": "usb/udc",
    "zephyr_udc_virtual": "usb/udc",
    #
    # usb/uhc
    "maxim_max3421e_spi": "usb/uhc",
    "zephyr_uhc_virtual": "usb/uhc",
    #
    # usb_c/ppc
    "nuvoton_numaker_ppc": "usb_c/ppc",
    "nxp_nx20p3483": "usb_c/ppc",
    #
    # usb_c/tcpc
    "nuvoton_numaker_tcpc": "usb_c/tcpc",
    "parade_ps8xxx": "usb_c/tcpc",
    "richtek_rt1715": "usb_c/tcpc",
    "st_stm32_ucpd": "usb_c/tcpc",
    #
    # usb_c/vbus
    "nuvoton_numaker_vbus": "usb_c/vbus",
    "zephyr_usb_c_vbus_adc": "usb_c/vbus",
    "zephyr_usb_c_vbus_tcpci": "usb_c/vbus",
    #
    # video
    "aptina_mt9m114": "video",
    "espressif_esp32_lcd_cam": "video",
    "galaxycore_gc2145": "video",
    "nxp_imx_csi": "video",
    "nxp_mipi_csi2rx": "video",
    "nxp_video_smartdma": "video",
    "ovti_ov2640": "video",
    "ovti_ov5640": "video",
    "ovti_ov7670": "video",
    "ovti_ov7725": "video",
    "st_stm32_dcmi": "video",
    "zephyr_sw_generator": "video",
    "zephyr_video_emul_imager": "video",
    "zephyr_video_emul_rx": "video",
    #
    # virtualization
    "qemu_ivshmem": "virtualization",
    #
    # w1
    "adi_max32_w1": "w1",
    "maxim_ds2482_800": "w1",
    "maxim_ds2482_800_channel": "w1",
    "maxim_ds2484": "w1",
    "maxim_ds2485": "w1",
    "vnd_w1": "w1",
    "zephyr_w1_gpio": "w1",
    "zephyr_w1_serial": "w1",
    #
    # watchdog
    "adi_max32_watchdog": "watchdog",
    "ambiq_watchdog": "watchdog",
    "andestech_atcwdt200": "watchdog",
    "arm_cmsdk_watchdog": "watchdog",
    "atmel_sam0_watchdog": "watchdog",
    "atmel_sam_watchdog": "watchdog",
    "ene_kb1200_watchdog": "watchdog",
    "espressif_esp32_watchdog": "watchdog",
    "espressif_esp32_xt_wdt": "watchdog",
    "gd_gd32_fwdgt": "watchdog",
    "gd_gd32_wwdgt": "watchdog",
    "infineon_cat1_watchdog": "watchdog",
    "infineon_xmc4xxx_watchdog": "watchdog",
    "intel_adsp_watchdog": "watchdog",
    "intel_tco_wdt": "watchdog",
    "ite_it8xxx2_watchdog": "watchdog",
    "litex_watchdog": "watchdog",
    "lowrisc_opentitan_aontimer": "watchdog",
    "microchip_xec_watchdog": "watchdog",
    "nordic_npm1300_wdt": "watchdog",
    "nordic_npm2100_wdt": "watchdog",
    "nordic_npm6001_wdt": "watchdog",
    "nuvoton_npcx_watchdog": "watchdog",
    "nuvoton_numaker_wwdt": "watchdog",
    "nxp_fs26_wdog": "watchdog",
    "nxp_imx_wdog": "watchdog",
    "nxp_kinetis_wdog": "watchdog",
    "nxp_lpc_wwdt": "watchdog",
    "nxp_s32_swt": "watchdog",
    "nxp_wdog32": "watchdog",
    "raspberrypi_pico_watchdog": "watchdog",
    "renesas_smartbond_watchdog": "watchdog",
    "sifive_wdt": "watchdog",
    "silabs_gecko_wdog": "watchdog",
    "snps_designware_watchdog": "watchdog",
    "st_stm32_watchdog": "watchdog",
    "st_stm32_window_watchdog": "watchdog",
    "ti_cc13xx_cc26xx_watchdog": "watchdog",
    "ti_cc32xx_watchdog": "watchdog",
    "ti_tps382x": "watchdog",
    "xlnx_xps_timebase_wdt_1_00_a": "watchdog",
    #
    # wifi/esp32/src
    "espressif_esp32_wifi": "wifi/esp32/src",
    #
    # wifi/esp_at
    "espressif_esp_at": "wifi/esp_at",
    #
    # wifi/eswifi
    "inventek_eswifi": "wifi/eswifi",
    "inventek_eswifi_uart": "wifi/eswifi",
    #
    # wifi/nrf_wifi/off_raw_tx/src
    "nordic_wlan": "wifi/nrf_wifi/off_raw_tx/src",
    #
    # wifi/nxp
    "nxp_wifi": "wifi/nxp",
    #
    # wifi/winc1500
    "atmel_winc1500": "wifi/winc1500",
}
