USB_VID = 0x239A
USB_PID = 0x80F4
USB_PRODUCT = "MTM Computer"
USB_MANUFACTURER = "Music Thing Modular"

CHIP_VARIANT = RP2040
CHIP_FAMILY = rp2

EXTERNAL_FLASH_DEVICES = "W25Q16JVxQ"

CIRCUITPY_AUDIODELAYS = 1
CIRCUITPY_IMAGECAPTURE = 0
CIRCUITPY_PICODVI = 0
