USB_VID = 0x2E8A
USB_PID = 0x10C1
USB_PRODUCT = "Workshop Computer"
USB_MANUFACTURER = "Music Thing Modular"

CHIP_VARIANT = RP2040
CHIP_FAMILY = rp2

EXTERNAL_FLASH_DEVICES = "W25Q16JVxQ"

CIRCUITPY_AUDIOEFFECTS = 1
CIRCUITPY_IMAGECAPTURE = 0
CIRCUITPY_PICODVI = 0
