USB_VID = 0x303a
USB_PID = 0x8154
USB_PRODUCT = "T-QT PRO NO PSRAM"
USB_MANUFACTURER = "LILYGO"

IDF_TARGET = esp32s3

CIRCUITPY_ESP_FLASH_MODE = qio
CIRCUITPY_ESP_FLASH_FREQ = 80m
CIRCUITPY_ESP_FLASH_SIZE = 8MB

CIRCUITPY_ESPCAMERA = 0
# Not enough pins.
CIRCUITPY_PARALLELDISPLAYBUS = 0
