USB_VID = 0x2E8A
USB_PID = 0x10B1
USB_PRODUCT = "RP2350-Plus"
USB_MANUFACTURER = "Waveshare Electronics"

CHIP_VARIANT = RP2350
CHIP_PACKAGE = A
CHIP_FAMILY = rp2

EXTERNAL_FLASH_DEVICES = "W25Q32JVxQ"

CIRCUITPY__EVE = 1
