USB_VID = 0x04D8 
USB_PID = 0xE5B3
USB_PRODUCT = "RAPID-0"
USB_MANUFACTURER = "Bruin Spacecraft Group"

CHIP_VARIANT = SAMD51N20A
CHIP_FAMILY = samd51

QSPI_FLASH_FILESYSTEM = 1
EXTERNAL_FLASH_DEVICES = "MX25L51245G"
LONGINT_IMPL = MPZ
